// <auto-generated />
using System;
using Centralization.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Centralization.Migrations
{
    [DbContext(typeof(MemorialContext))]
    [Migration("20200804143649_updateIDs")]
    partial class updateIDs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Centralization.Models.LinkedInterment", b =>
                {
                    b.Property<int>("LinkedIntermentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CemNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Idf")
                        .HasColumnType("int");

                    b.Property<int>("MemorialApplicationID")
                        .HasColumnType("int");

                    b.HasKey("LinkedIntermentID");

                    b.HasIndex("MemorialApplicationID");

                    b.ToTable("LinkedInterments");
                });

            modelBuilder.Entity("Centralization.Models.MemorialApplication", b =>
                {
                    b.Property<int>("MemorialApplicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CemNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploadedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MemorialApplicationID");

                    b.ToTable("MemorialApplications");
                });

            modelBuilder.Entity("Centralization.Models.LinkedInterment", b =>
                {
                    b.HasOne("Centralization.Models.MemorialApplication", "MemorialApplication")
                        .WithMany("LinkedInterments")
                        .HasForeignKey("MemorialApplicationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
