using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace Centralization.Models
{
    public class Cemeteries
    {
        /// <summary>
        /// Dictionary for parent cemetery names in format of folder name for paths
        /// </summary>
        public static Dictionary<string, string> parentCems = new Dictionary<string, string>()
        {
            { "01", "CALVARY" },
            { "02", "SAINT CASIMIR" },
            { "03", "QUEEN OF HEAVEN" },
            { "04", "HOLY SEPULCHRE" },
            { "05", "ALL SAINTS" },
            { "06", "ASCENSION" },
            { "07", "QUEEN OF HEAVEN" },
            { "08", "ASSUMPTION" },
            { "10", "QUEEN OF HEAVEN" },
            { "11", "SAINT CASIMIR" },
            { "12", "SAINT CASIMIR" },
            { "14", "ASCENSION" },
            { "15", "ASCENSION" },
            { "16", "ASCENSION" },
            { "17", "GOOD SHEPHERD" },
            { "18", "ASCENSION" },
            { "19", "ASSUMPTION" },
            { "21", "ASSUMPTION" },
            { "22", "ASCENSION" },
            { "23", "CALVARY" },
            { "24", "CALVARY" },
            { "25", "ASCENSION" },
            { "26", "ASSUMPTION" },
            { "27", "ASCENSION" },
            { "28", "ASCENSION" },
            { "29", "ASCENSION" },
            { "31", "CALVARY" },
            { "32", "SAINT JOSEPH" },
            { "33", "SAINT MARY" },
            { "34", "SAINT MICHAEL" },
            { "35", "CALVARY" },
            { "40", "SAINT ADALBERT" },
            { "41", "HOLY CROSS" },
            { "42", "MARYHILL" },
            { "43", "RESURRECTION" },
            { "44", "RESURRECTION" },
            { "45", "SAINT CASIMIR" },
            { "46", "ASCENSION" },
            { "47", "ASCENSION" },
            { "48", "GOOD SHEPHERD" },
            { "49", "GOOD SHEPHERD" },
            { "50", "ALL SAINTS" },
            { "51", "GOOD SHEPHERD" },
            { "53", "GOOD SHEPHERD" },
            { "54", "GOOD SHEPHERD" },
            { "55", "SAINT ADALBERT" },
            { "56", "SAINT CASIMIR" }
        };

        public static Dictionary<string, string> cems = new Dictionary<string, string>()
        {
            { "01", "Calvary" },
            { "02", "Mount Olivet" },
            { "03", "Mount Carmel" },
            { "04", "Holy Sepulchre" },
            { "05", "All Saints" },
            { "06", "Ascension" },
            { "07", "Queen Of Heaven" },
            { "08", "Assumption" },
            { "10", "Queen of Heaven Mausoleum" },
            { "11", "St. Gabriel" },
            { "12", "St. Benedict" },
            { "14", "St. Mary, Highland Park" },
            { "15", "St. Mary, Lake Forest" },
            { "16", "St. Mary, Waukegan" },
            { "17", "St. Patrick, Lemont" },
            { "18", "Transfiguration, Wauconda" },
            { "19", "St. Anne, Park Forest" },
            { "21", "Calvary, Steger" },
            { "22", "Sacred Heart, Northbrook" },
            { "23", "St. Joseph, Wilmette" },
            { "24", "St. Peter, Skokie" },
            { "25", "St. Joseph, Round Lake" },
            { "26", "St. James, Sauk Village" },
            { "27", "St. Mary, Fremont Center" },
            { "28", "St. Patrick, West Lake Forest" },
            { "29", "St. Bede, Fox Lake" },
            { "31", "St. Boniface" },
            { "32", "St. Joseph" },
            { "33", "St. Mary" },
            { "34", "St. Michael" },
            { "35", "St. Henry, Chicago" },
            { "40", "St. Adalbert" },
            { "41", "Holy Cross" },
            { "42", "Maryhill" },
            { "43", "Resurrection" },
            { "44", "Resurrection Mausoleum" },
            { "45", "St. Casimir" },
            { "46", "St. Patrick, Wadsworth" },
            { "47", "St. Peter, Volo" },
            { "48", "St. Michael, Orland Park" },
            { "49", "SS. Cyril & Methodius, Lemont" },
            { "50", "All Saints Mausoleum" },
            { "51", "St. Alphonsus, Lemont" },
            { "53", "St. James Sag Bridge, Lemont" },
            { "54", "Good Shepard" },
            { "55", "Norwood Park" },
            { "56", "Sacred Heart, Palos Hills" }
        };

        public static List<SelectListItem> cemeteriesSelectList = new List<SelectListItem>
        {
            new SelectListItem() {Text = "All Saints", Value = "05" },
            new SelectListItem() {Text = "All Saints Mausoleum", Value = "50" },
            new SelectListItem() {Text = "Ascension", Value = "06" },
            new SelectListItem() {Text = "Assumption", Value = "08" },
            new SelectListItem() {Text = "Calvary", Value = "01" },
            new SelectListItem() {Text = "Calvary, Steger", Value = "21" },
            new SelectListItem() {Text = "Good Shepherd", Value = "54" },
            new SelectListItem() {Text = "Holy Cross", Value = "41" },
            new SelectListItem() {Text = "Holy Sepulchre", Value = "04" },
            new SelectListItem() {Text = "Maryhill", Value = "42" },
            new SelectListItem() {Text = "Mount Carmel", Value = "03" },
            new SelectListItem() {Text = "Mount Olivet", Value = "02" },
            new SelectListItem() {Text = "Norwood Park", Value = "55" },
            new SelectListItem() {Text = "Queen of Heaven", Value = "07" },
            new SelectListItem() {Text = "Queen of Heaven Mausoleum", Value = "10" },
            new SelectListItem() {Text = "Resurrection", Value = "43" },
            new SelectListItem() {Text = "Resurrection Mausoluem", Value = "44" },
            new SelectListItem() {Text = "Sacred Heart, Northbrook", Value = "22" },
            new SelectListItem() {Text = "Sacred Heart, Palos Hills", Value = "56" },
            new SelectListItem() {Text = "St. Adalbert", Value = "40" },
            new SelectListItem() {Text = "St. Alphonsus, Lemont", Value = "51" },
            new SelectListItem() {Text = "St. Anne, Park Forest", Value = "19" },
            new SelectListItem() {Text = "St. Bede, Fox Lake", Value = "29" },
            new SelectListItem() {Text = "St. Benedict", Value = "12" },
            new SelectListItem() {Text = "St. Boniface", Value = "31" },
            new SelectListItem() {Text = "St. Casimir", Value = "45" },
            new SelectListItem() {Text = "St. Gabriel", Value = "11" },
            new SelectListItem() {Text = "St. Henry, Chicago", Value = "35" },
            new SelectListItem() {Text = "St. James Sag Bridge, Lemont", Value = "53" },
            new SelectListItem() {Text = "St. James, Sauk Village", Value = "26" },
            new SelectListItem() {Text = "St. Joseph", Value = "32" },
            new SelectListItem() {Text = "St. Joseph, Round Lake", Value = "25" },
            new SelectListItem() {Text = "St. Joseph, Wilmette", Value = "23" },
            new SelectListItem() {Text = "St. Mary", Value = "33" },
            new SelectListItem() {Text = "St. Mary, Fremont Center", Value = "27" },
            new SelectListItem() {Text = "St. Mary, Highland Park", Value = "14" },
            new SelectListItem() {Text = "St. Mary, Lake Forest", Value = "15" },
            new SelectListItem() {Text = "St. Mary, Waukegan", Value = "16" },
            new SelectListItem() {Text = "St. Michael", Value = "34" },
            new SelectListItem() {Text = "St. Michael, Orland Park", Value = "48" },
            new SelectListItem() {Text = "St. Patrick, Lemont", Value = "17" },
            new SelectListItem() {Text = "St. Patrick, Wadsworth", Value = "46" },
            new SelectListItem() {Text = "St. Patrick, West Lake Forest", Value = "28" },
            new SelectListItem() {Text = "St. Peter, Skokie", Value = "24" },
            new SelectListItem() {Text = "St. Peter, Volo", Value = "47" },
            new SelectListItem() {Text = "SS. Cyril & Methodius, Lemont", Value = "49" },
            new SelectListItem() {Text = "Transfiguration, Wauconda", Value = "18" }
        };
    }
}
